# Copyright 2015-2016 Harri Kapanen <harri.kapanen@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Check for existing Node.js install
  stat:
    path: "{{ nodejs_armv6_binary }}"
  register: node_exists

- name: Get installed Node.js version
  command: "{{ nodejs_armv6_binary }} --version"
  register: installed_node_version
  when: "node_exists.stat.exists"
  changed_when: False
  failed_when: False

- name: Get latest available Node.js tarball filename
  shell: curl https://nodejs.org/dist/{{ nodejs_armv6_version }}/ | grep armv6l.tar.gz | sed 's/.*>\(.*\)<\/a>.*/\1/g' || /bin/true
  args:
    warn: False
  register: latest_node_filename
  changed_when: False

- name: Get latest available Node.js version
  set_fact:
    latest_node_version: "{{ latest_node_filename.stdout | regex_search('node-(.*)-linux-armv6l.tar.gz', '\\1') | first }}"
  when: latest_node_filename.stdout != ""

- name: Install Node.js
  block:
  - name: Generate download URL
    set_fact: node_download_url=https://nodejs.org/dist/{{ nodejs_armv6_version }}/node-{{ latest_node_version }}-linux-armv6l.tar.gz

  - name: Download Node.js binary distribution
    get_url: url={{ node_download_url }} dest=/tmp/nodejs.tar.gz mode=0440

  - name: Extract distribution package to /usr/local
    shell: tar xzf /tmp/nodejs.tar.gz -C /usr/local --strip-components=1 --no-same-owner
    args:
      warn: False

  - name: Link binary to /usr/bin/node
    file: src=/usr/local/bin/node dest=/usr/bin/node state=link force=yes

  - name: Clear temporary files
    file: path=/tmp/nodejs.tar.gz state=absent

  when: (not node_exists.stat.exists)
        or (latest_node_version is defined and (latest_node_version != installed_node_version.stdout))
